### ISSUE TITLE
warning: address of stack memory associated with local variable

### ISSUE THREAD

**Issue by batalibg** [notgiven688/webminerpool#69]
warning: address of stack memory associated with local variable

'output' returned [-Wreturn-stack-address]

return &output[0];

^~~~~~

1 warning generated.

Exception in thread Thread-3:

Traceback (most recent call last):

File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner

self.run()

File "/usr/lib/python2.7/threading.py", line 754, in run

self.__target(*self.__args, **self.__kwargs)

File "/usr/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results

task = get()

TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())

I've come to here. And no progress :( :( :( how to fix this? :(

**Comment by notgiven688** [comment]
1) A warning is not error. You *can* ignore it.
2) What exactly are you doing?
3) Returning the local defined variable works for the emcc generated webasm code. I should probably implement it in a cleaner way.

**Comment by batalibg** [comment]
I trying to compile wasm with emcc form folder "webassembly" with command "emcc main.c" on Ubuntu 14 LTS terminal. And give this warning and no progress...

**Comment by notgiven688** [comment]
There is a makefile which maybe works. Try a simple "make".

**Comment by batalibg** [comment]
I trying and then: 

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())

This and no progres.... :(

**Comment by notgiven688** [comment]
Are you able to compile anything (e.g. a "hello world" program) with emscripten?

**Comment by batalibg** [comment]
No, Totally noob :(

**Comment by notgiven688** [comment]
Also: you do not need to compile it yourself if you just want to run the miner. Everything is included in the SDK folder.

**Comment by batalibg** [comment]
Thanks you
